window.esdocSearchIndex = [
  [
    "vibejs/src/directory/directory.js~directory",
    "class/src/directory/Directory.js~Directory.html",
    "<span>Directory</span> <span class=\"search-result-import-path\">vibejs/src/directory/Directory.js</span>",
    "class"
  ],
  [
    "vibejs/src/directory/directorymutation.js~directorymutation",
    "class/src/directory/DirectoryMutation.js~DirectoryMutation.html",
    "<span>DirectoryMutation</span> <span class=\"search-result-import-path\">vibejs/src/directory/DirectoryMutation.js</span>",
    "class"
  ],
  [
    "vibejs/src/directory/directorysubject.js~directorysubject",
    "class/src/directory/DirectorySubject.js~DirectorySubject.html",
    "<span>DirectorySubject</span> <span class=\"search-result-import-path\">vibejs/src/directory/DirectorySubject.js</span>",
    "class"
  ],
  [
    "vibejs/src/entitystore.js~entitystore",
    "class/src/EntityStore.js~EntityStore.html",
    "<span>EntityStore</span> <span class=\"search-result-import-path\">vibejs/src/EntityStore.js</span>",
    "class"
  ],
  [
    "vibejs/src/entity/entitysubject.js~entitysubject",
    "class/src/entity/EntitySubject.js~EntitySubject.html",
    "<span>EntitySubject</span> <span class=\"search-result-import-path\">vibejs/src/entity/EntitySubject.js</span>",
    "class"
  ],
  [
    "vibejs/src/entity/model.js~model",
    "class/src/entity/Model.js~Model.html",
    "<span>Model</span> <span class=\"search-result-import-path\">vibejs/src/entity/Model.js</span>",
    "class"
  ],
  [
    "vibejs/src/entity/mutation.js~mutation",
    "class/src/entity/Mutation.js~Mutation.html",
    "<span>Mutation</span> <span class=\"search-result-import-path\">vibejs/src/entity/Mutation.js</span>",
    "class"
  ],
  [
    "vibejs/src/functions/createreactiveinterface.js~createreactiveinterface",
    "function/index.html#static-function-createReactiveInterface",
    "<span>createReactiveInterface</span> <span class=\"search-result-import-path\">vibejs/src/functions/createReactiveInterface.js</span>",
    "function"
  ],
  [
    "vibejs/src/functions/extendarray.js~extendarray",
    "function/index.html#static-function-extendArray",
    "<span>extendArray</span> <span class=\"search-result-import-path\">vibejs/src/functions/extendArray.js</span>",
    "function"
  ],
  [
    "vibejs/src/functions/typechecker.js~isattribute",
    "function/index.html#static-function-isAttribute",
    "<span>isAttribute</span> <span class=\"search-result-import-path\">vibejs/src/functions/typeChecker.js</span>",
    "function"
  ],
  [
    "vibejs/src/functions/typechecker.js~isattributearray",
    "function/index.html#static-function-isAttributeArray",
    "<span>isAttributeArray</span> <span class=\"search-result-import-path\">vibejs/src/functions/typeChecker.js</span>",
    "function"
  ],
  [
    "vibejs/src/functions/typechecker.js~isidentifier",
    "function/index.html#static-function-isIdentifier",
    "<span>isIdentifier</span> <span class=\"search-result-import-path\">vibejs/src/functions/typeChecker.js</span>",
    "function"
  ],
  [
    "vibejs/src/functions/typechecker.js~isreference",
    "function/index.html#static-function-isReference",
    "<span>isReference</span> <span class=\"search-result-import-path\">vibejs/src/functions/typeChecker.js</span>",
    "function"
  ],
  [
    "vibejs/src/functions/typechecker.js~isreferencearray",
    "function/index.html#static-function-isReferenceArray",
    "<span>isReferenceArray</span> <span class=\"search-result-import-path\">vibejs/src/functions/typeChecker.js</span>",
    "function"
  ],
  [
    "vibejs/src/functions/setcomputedproperty.js~setcomputedproperty",
    "function/index.html#static-function-setComputedProperty",
    "<span>setComputedProperty</span> <span class=\"search-result-import-path\">vibejs/src/functions/setComputedProperty.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/entitystore.js",
    "file/src/EntityStore.js.html",
    "src/EntityStore.js",
    "file"
  ],
  [
    "src/entitystore.js~entitystore#_createentitysubject",
    "class/src/EntityStore.js~EntityStore.html#instance-method-_createEntitySubject",
    "src/EntityStore.js~EntityStore#_createEntitySubject",
    "method"
  ],
  [
    "src/entitystore.js~entitystore#_modelsarray",
    "class/src/EntityStore.js~EntityStore.html#instance-member-_modelsArray",
    "src/EntityStore.js~EntityStore#_modelsArray",
    "member"
  ],
  [
    "src/entitystore.js~entitystore#_setupmodelsandheap",
    "class/src/EntityStore.js~EntityStore.html#instance-method-_setupModelsAndHeap",
    "src/EntityStore.js~EntityStore#_setupModelsAndHeap",
    "method"
  ],
  [
    "src/entitystore.js~entitystore#allentities",
    "class/src/EntityStore.js~EntityStore.html#instance-method-allEntities",
    "src/EntityStore.js~EntityStore#allEntities",
    "method"
  ],
  [
    "src/entitystore.js~entitystore#clear",
    "class/src/EntityStore.js~EntityStore.html#instance-method-clear",
    "src/EntityStore.js~EntityStore#clear",
    "method"
  ],
  [
    "src/entitystore.js~entitystore#constructor",
    "class/src/EntityStore.js~EntityStore.html#instance-constructor-constructor",
    "src/EntityStore.js~EntityStore#constructor",
    "method"
  ],
  [
    "src/entitystore.js~entitystore#deleteentity",
    "class/src/EntityStore.js~EntityStore.html#instance-method-deleteEntity",
    "src/EntityStore.js~EntityStore#deleteEntity",
    "method"
  ],
  [
    "src/entitystore.js~entitystore#entityupdated",
    "class/src/EntityStore.js~EntityStore.html#instance-method-entityUpdated",
    "src/EntityStore.js~EntityStore#entityUpdated",
    "method"
  ],
  [
    "src/entitystore.js~entitystore#getorcreateentitysubject",
    "class/src/EntityStore.js~EntityStore.html#instance-method-getOrCreateEntitySubject",
    "src/EntityStore.js~EntityStore#getOrCreateEntitySubject",
    "method"
  ],
  [
    "src/entitystore.js~entitystore#heap",
    "class/src/EntityStore.js~EntityStore.html#instance-member-heap",
    "src/EntityStore.js~EntityStore#heap",
    "member"
  ],
  [
    "src/entitystore.js~entitystore#models",
    "class/src/EntityStore.js~EntityStore.html#instance-member-models",
    "src/EntityStore.js~EntityStore#models",
    "member"
  ],
  [
    "src/entitystore.js~entitystore#observables",
    "class/src/EntityStore.js~EntityStore.html#instance-member-observables",
    "src/EntityStore.js~EntityStore#observables",
    "member"
  ],
  [
    "src/entitystore.js~entitystore#putentity",
    "class/src/EntityStore.js~EntityStore.html#instance-method-putEntity",
    "src/EntityStore.js~EntityStore#putEntity",
    "method"
  ],
  [
    "src/entitystore.js~entitystore#updateentity",
    "class/src/EntityStore.js~EntityStore.html#instance-method-updateEntity",
    "src/EntityStore.js~EntityStore#updateEntity",
    "method"
  ],
  [
    "src/directory/directory.js",
    "file/src/directory/Directory.js.html",
    "src/directory/Directory.js",
    "file"
  ],
  [
    "src/directory/directory.js~directory#clear",
    "class/src/directory/Directory.js~Directory.html#instance-method-clear",
    "src/directory/Directory.js~Directory#clear",
    "method"
  ],
  [
    "src/directory/directory.js~directory#computed",
    "class/src/directory/Directory.js~Directory.html#instance-member-computed",
    "src/directory/Directory.js~Directory#computed",
    "member"
  ],
  [
    "src/directory/directory.js~directory#constructor",
    "class/src/directory/Directory.js~Directory.html#instance-constructor-constructor",
    "src/directory/Directory.js~Directory#constructor",
    "method"
  ],
  [
    "src/directory/directory.js~directory#initialstate",
    "class/src/directory/Directory.js~Directory.html#instance-method-initialState",
    "src/directory/Directory.js~Directory#initialState",
    "method"
  ],
  [
    "src/directory/directory.js~directory#mutations",
    "class/src/directory/Directory.js~Directory.html#instance-member-mutations",
    "src/directory/Directory.js~Directory#mutations",
    "member"
  ],
  [
    "src/directory/directory.js~directory#name",
    "class/src/directory/Directory.js~Directory.html#instance-member-name",
    "src/directory/Directory.js~Directory#name",
    "member"
  ],
  [
    "src/directory/directory.js~directory#observe",
    "class/src/directory/Directory.js~Directory.html#instance-method-observe",
    "src/directory/Directory.js~Directory#observe",
    "method"
  ],
  [
    "src/directory/directory.js~directory#state",
    "class/src/directory/Directory.js~Directory.html#instance-member-state",
    "src/directory/Directory.js~Directory#state",
    "member"
  ],
  [
    "src/directory/directory.js~directory#store",
    "class/src/directory/Directory.js~Directory.html#instance-member-store",
    "src/directory/Directory.js~Directory#store",
    "member"
  ],
  [
    "src/directory/directory.js~directory#structure",
    "class/src/directory/Directory.js~Directory.html#instance-member-structure",
    "src/directory/Directory.js~Directory#structure",
    "member"
  ],
  [
    "src/directory/directory.js~directory#subject",
    "class/src/directory/Directory.js~Directory.html#instance-member-subject",
    "src/directory/Directory.js~Directory#subject",
    "member"
  ],
  [
    "src/directory/directorymutation.js",
    "file/src/directory/DirectoryMutation.js.html",
    "src/directory/DirectoryMutation.js",
    "file"
  ],
  [
    "src/directory/directorymutation.js~directorymutation#commit",
    "class/src/directory/DirectoryMutation.js~DirectoryMutation.html#instance-method-commit",
    "src/directory/DirectoryMutation.js~DirectoryMutation#commit",
    "method"
  ],
  [
    "src/directory/directorymutation.js~directorymutation#constructor",
    "class/src/directory/DirectoryMutation.js~DirectoryMutation.html#instance-constructor-constructor",
    "src/directory/DirectoryMutation.js~DirectoryMutation#constructor",
    "method"
  ],
  [
    "src/directory/directorymutation.js~directorymutation#resultstate",
    "class/src/directory/DirectoryMutation.js~DirectoryMutation.html#instance-member-resultState",
    "src/directory/DirectoryMutation.js~DirectoryMutation#resultState",
    "member"
  ],
  [
    "src/directory/directorymutation.js~directorymutation#subject",
    "class/src/directory/DirectoryMutation.js~DirectoryMutation.html#instance-member-subject",
    "src/directory/DirectoryMutation.js~DirectoryMutation#subject",
    "member"
  ],
  [
    "src/directory/directorysubject.js",
    "file/src/directory/DirectorySubject.js.html",
    "src/directory/DirectorySubject.js",
    "file"
  ],
  [
    "src/directory/directorysubject.js~directorysubject#_applycomputed",
    "class/src/directory/DirectorySubject.js~DirectorySubject.html#instance-method-_applyComputed",
    "src/directory/DirectorySubject.js~DirectorySubject#_applyComputed",
    "method"
  ],
  [
    "src/directory/directorysubject.js~directorysubject#_applymutations",
    "class/src/directory/DirectorySubject.js~DirectorySubject.html#instance-method-_applyMutations",
    "src/directory/DirectorySubject.js~DirectorySubject#_applyMutations",
    "method"
  ],
  [
    "src/directory/directorysubject.js~directorysubject#_asobject",
    "class/src/directory/DirectorySubject.js~DirectorySubject.html#instance-method-_asObject",
    "src/directory/DirectorySubject.js~DirectorySubject#_asObject",
    "method"
  ],
  [
    "src/directory/directorysubject.js~directorysubject#_mapobservertosource",
    "class/src/directory/DirectorySubject.js~DirectorySubject.html#instance-method-_mapObserverToSource",
    "src/directory/DirectorySubject.js~DirectorySubject#_mapObserverToSource",
    "method"
  ],
  [
    "src/directory/directorysubject.js~directorysubject#asobject",
    "class/src/directory/DirectorySubject.js~DirectorySubject.html#instance-method-asObject",
    "src/directory/DirectorySubject.js~DirectorySubject#asObject",
    "method"
  ],
  [
    "src/directory/directorysubject.js~directorysubject#constructor",
    "class/src/directory/DirectorySubject.js~DirectorySubject.html#instance-constructor-constructor",
    "src/directory/DirectorySubject.js~DirectorySubject#constructor",
    "method"
  ],
  [
    "src/directory/directorysubject.js~directorysubject#createreactiveinterface",
    "class/src/directory/DirectorySubject.js~DirectorySubject.html#instance-method-createReactiveInterface",
    "src/directory/DirectorySubject.js~DirectorySubject#createReactiveInterface",
    "method"
  ],
  [
    "src/directory/directorysubject.js~directorysubject#directory",
    "class/src/directory/DirectorySubject.js~DirectorySubject.html#instance-member-directory",
    "src/directory/DirectorySubject.js~DirectorySubject#directory",
    "member"
  ],
  [
    "src/directory/directorysubject.js~directorysubject#equals",
    "class/src/directory/DirectorySubject.js~DirectorySubject.html#instance-method-equals",
    "src/directory/DirectorySubject.js~DirectorySubject#equals",
    "method"
  ],
  [
    "src/directory/directorysubject.js~directorysubject#interface",
    "class/src/directory/DirectorySubject.js~DirectorySubject.html#instance-member-interface",
    "src/directory/DirectorySubject.js~DirectorySubject#interface",
    "member"
  ],
  [
    "src/directory/directorysubject.js~directorysubject#issubscriberof",
    "class/src/directory/DirectorySubject.js~DirectorySubject.html#instance-method-isSubscriberOf",
    "src/directory/DirectorySubject.js~DirectorySubject#isSubscriberOf",
    "method"
  ],
  [
    "src/directory/directorysubject.js~directorysubject#mutate",
    "class/src/directory/DirectorySubject.js~DirectorySubject.html#instance-method-mutate",
    "src/directory/DirectorySubject.js~DirectorySubject#mutate",
    "method"
  ],
  [
    "src/directory/directorysubject.js~directorysubject#observable",
    "class/src/directory/DirectorySubject.js~DirectorySubject.html#instance-member-observable",
    "src/directory/DirectorySubject.js~DirectorySubject#observable",
    "member"
  ],
  [
    "src/directory/directorysubject.js~directorysubject#store",
    "class/src/directory/DirectorySubject.js~DirectorySubject.html#instance-member-store",
    "src/directory/DirectorySubject.js~DirectorySubject#store",
    "member"
  ],
  [
    "src/directory/directorysubject.js~directorysubject#subscribe",
    "class/src/directory/DirectorySubject.js~DirectorySubject.html#instance-method-subscribe",
    "src/directory/DirectorySubject.js~DirectorySubject#subscribe",
    "method"
  ],
  [
    "src/directory/directorysubject.js~directorysubject#subscriptions",
    "class/src/directory/DirectorySubject.js~DirectorySubject.html#instance-member-subscriptions",
    "src/directory/DirectorySubject.js~DirectorySubject#subscriptions",
    "member"
  ],
  [
    "src/directory/directorysubject.js~directorysubject#tostring",
    "class/src/directory/DirectorySubject.js~DirectorySubject.html#instance-method-toString",
    "src/directory/DirectorySubject.js~DirectorySubject#toString",
    "method"
  ],
  [
    "src/directory/directorysubject.js~directorysubject#unsubscribe",
    "class/src/directory/DirectorySubject.js~DirectorySubject.html#instance-method-unsubscribe",
    "src/directory/DirectorySubject.js~DirectorySubject#unsubscribe",
    "method"
  ],
  [
    "src/directory/directorysubject.js~directorysubject#update",
    "class/src/directory/DirectorySubject.js~DirectorySubject.html#instance-method-update",
    "src/directory/DirectorySubject.js~DirectorySubject#update",
    "method"
  ],
  [
    "src/directory/directorysubject.js~directorysubject#updateinterface",
    "class/src/directory/DirectorySubject.js~DirectorySubject.html#instance-method-updateInterface",
    "src/directory/DirectorySubject.js~DirectorySubject#updateInterface",
    "method"
  ],
  [
    "src/entity/entitysubject.js",
    "file/src/entity/EntitySubject.js.html",
    "src/entity/EntitySubject.js",
    "file"
  ],
  [
    "src/entity/entitysubject.js~entitysubject#_applycomputed",
    "class/src/entity/EntitySubject.js~EntitySubject.html#instance-method-_applyComputed",
    "src/entity/EntitySubject.js~EntitySubject#_applyComputed",
    "method"
  ],
  [
    "src/entity/entitysubject.js~entitysubject#_applymutations",
    "class/src/entity/EntitySubject.js~EntitySubject.html#instance-method-_applyMutations",
    "src/entity/EntitySubject.js~EntitySubject#_applyMutations",
    "method"
  ],
  [
    "src/entity/entitysubject.js~entitysubject#_asobject",
    "class/src/entity/EntitySubject.js~EntitySubject.html#instance-method-_asObject",
    "src/entity/EntitySubject.js~EntitySubject#_asObject",
    "method"
  ],
  [
    "src/entity/entitysubject.js~entitysubject#_mapobservertosource",
    "class/src/entity/EntitySubject.js~EntitySubject.html#instance-method-_mapObserverToSource",
    "src/entity/EntitySubject.js~EntitySubject#_mapObserverToSource",
    "method"
  ],
  [
    "src/entity/entitysubject.js~entitysubject#_processreference",
    "class/src/entity/EntitySubject.js~EntitySubject.html#instance-method-_processReference",
    "src/entity/EntitySubject.js~EntitySubject#_processReference",
    "method"
  ],
  [
    "src/entity/entitysubject.js~entitysubject#asobject",
    "class/src/entity/EntitySubject.js~EntitySubject.html#instance-method-asObject",
    "src/entity/EntitySubject.js~EntitySubject#asObject",
    "method"
  ],
  [
    "src/entity/entitysubject.js~entitysubject#constructor",
    "class/src/entity/EntitySubject.js~EntitySubject.html#instance-constructor-constructor",
    "src/entity/EntitySubject.js~EntitySubject#constructor",
    "method"
  ],
  [
    "src/entity/entitysubject.js~entitysubject#createreactiveinterface",
    "class/src/entity/EntitySubject.js~EntitySubject.html#instance-method-createReactiveInterface",
    "src/entity/EntitySubject.js~EntitySubject#createReactiveInterface",
    "method"
  ],
  [
    "src/entity/entitysubject.js~entitysubject#equals",
    "class/src/entity/EntitySubject.js~EntitySubject.html#instance-method-equals",
    "src/entity/EntitySubject.js~EntitySubject#equals",
    "method"
  ],
  [
    "src/entity/entitysubject.js~entitysubject#id",
    "class/src/entity/EntitySubject.js~EntitySubject.html#instance-member-id",
    "src/entity/EntitySubject.js~EntitySubject#id",
    "member"
  ],
  [
    "src/entity/entitysubject.js~entitysubject#interface",
    "class/src/entity/EntitySubject.js~EntitySubject.html#instance-member-interface",
    "src/entity/EntitySubject.js~EntitySubject#interface",
    "member"
  ],
  [
    "src/entity/entitysubject.js~entitysubject#issubscriberof",
    "class/src/entity/EntitySubject.js~EntitySubject.html#instance-method-isSubscriberOf",
    "src/entity/EntitySubject.js~EntitySubject#isSubscriberOf",
    "method"
  ],
  [
    "src/entity/entitysubject.js~entitysubject#model",
    "class/src/entity/EntitySubject.js~EntitySubject.html#instance-member-model",
    "src/entity/EntitySubject.js~EntitySubject#model",
    "member"
  ],
  [
    "src/entity/entitysubject.js~entitysubject#mutate",
    "class/src/entity/EntitySubject.js~EntitySubject.html#instance-method-mutate",
    "src/entity/EntitySubject.js~EntitySubject#mutate",
    "method"
  ],
  [
    "src/entity/entitysubject.js~entitysubject#name",
    "class/src/entity/EntitySubject.js~EntitySubject.html#instance-member-name",
    "src/entity/EntitySubject.js~EntitySubject#name",
    "member"
  ],
  [
    "src/entity/entitysubject.js~entitysubject#observable",
    "class/src/entity/EntitySubject.js~EntitySubject.html#instance-member-observable",
    "src/entity/EntitySubject.js~EntitySubject#observable",
    "member"
  ],
  [
    "src/entity/entitysubject.js~entitysubject#store",
    "class/src/entity/EntitySubject.js~EntitySubject.html#instance-member-store",
    "src/entity/EntitySubject.js~EntitySubject#store",
    "member"
  ],
  [
    "src/entity/entitysubject.js~entitysubject#subscribe",
    "class/src/entity/EntitySubject.js~EntitySubject.html#instance-method-subscribe",
    "src/entity/EntitySubject.js~EntitySubject#subscribe",
    "method"
  ],
  [
    "src/entity/entitysubject.js~entitysubject#subscriptions",
    "class/src/entity/EntitySubject.js~EntitySubject.html#instance-member-subscriptions",
    "src/entity/EntitySubject.js~EntitySubject#subscriptions",
    "member"
  ],
  [
    "src/entity/entitysubject.js~entitysubject#tostring",
    "class/src/entity/EntitySubject.js~EntitySubject.html#instance-method-toString",
    "src/entity/EntitySubject.js~EntitySubject#toString",
    "method"
  ],
  [
    "src/entity/entitysubject.js~entitysubject#unsubscribe",
    "class/src/entity/EntitySubject.js~EntitySubject.html#instance-method-unsubscribe",
    "src/entity/EntitySubject.js~EntitySubject#unsubscribe",
    "method"
  ],
  [
    "src/entity/entitysubject.js~entitysubject#updateinterface",
    "class/src/entity/EntitySubject.js~EntitySubject.html#instance-method-updateInterface",
    "src/entity/EntitySubject.js~EntitySubject#updateInterface",
    "method"
  ],
  [
    "src/entity/model.js",
    "file/src/entity/Model.js.html",
    "src/entity/Model.js",
    "file"
  ],
  [
    "src/entity/model.js~model#allentities",
    "class/src/entity/Model.js~Model.html#instance-method-allEntities",
    "src/entity/Model.js~Model#allEntities",
    "method"
  ],
  [
    "src/entity/model.js~model#attachstore",
    "class/src/entity/Model.js~Model.html#instance-method-attachStore",
    "src/entity/Model.js~Model#attachStore",
    "method"
  ],
  [
    "src/entity/model.js~model#computed",
    "class/src/entity/Model.js~Model.html#instance-member-computed",
    "src/entity/Model.js~Model#computed",
    "member"
  ],
  [
    "src/entity/model.js~model#constructor",
    "class/src/entity/Model.js~Model.html#instance-constructor-constructor",
    "src/entity/Model.js~Model#constructor",
    "method"
  ],
  [
    "src/entity/model.js~model#filldefaultvalues",
    "class/src/entity/Model.js~Model.html#instance-method-fillDefaultValues",
    "src/entity/Model.js~Model#fillDefaultValues",
    "method"
  ],
  [
    "src/entity/model.js~model#insertentity",
    "class/src/entity/Model.js~Model.html#instance-method-insertEntity",
    "src/entity/Model.js~Model#insertEntity",
    "method"
  ],
  [
    "src/entity/model.js~model#mutations",
    "class/src/entity/Model.js~Model.html#instance-member-mutations",
    "src/entity/Model.js~Model#mutations",
    "member"
  ],
  [
    "src/entity/model.js~model#name",
    "class/src/entity/Model.js~Model.html#instance-member-name",
    "src/entity/Model.js~Model#name",
    "member"
  ],
  [
    "src/entity/model.js~model#observe",
    "class/src/entity/Model.js~Model.html#instance-method-observe",
    "src/entity/Model.js~Model#observe",
    "method"
  ],
  [
    "src/entity/model.js~model#store",
    "class/src/entity/Model.js~Model.html#instance-member-store",
    "src/entity/Model.js~Model#store",
    "member"
  ],
  [
    "src/entity/model.js~model#structure",
    "class/src/entity/Model.js~Model.html#instance-member-structure",
    "src/entity/Model.js~Model#structure",
    "member"
  ],
  [
    "src/entity/mutation.js",
    "file/src/entity/Mutation.js.html",
    "src/entity/Mutation.js",
    "file"
  ],
  [
    "src/entity/mutation.js~mutation#commit",
    "class/src/entity/Mutation.js~Mutation.html#instance-method-commit",
    "src/entity/Mutation.js~Mutation#commit",
    "method"
  ],
  [
    "src/entity/mutation.js~mutation#constructor",
    "class/src/entity/Mutation.js~Mutation.html#instance-constructor-constructor",
    "src/entity/Mutation.js~Mutation#constructor",
    "method"
  ],
  [
    "src/entity/mutation.js~mutation#resultstate",
    "class/src/entity/Mutation.js~Mutation.html#instance-member-resultState",
    "src/entity/Mutation.js~Mutation#resultState",
    "member"
  ],
  [
    "src/entity/mutation.js~mutation#subject",
    "class/src/entity/Mutation.js~Mutation.html#instance-member-subject",
    "src/entity/Mutation.js~Mutation#subject",
    "member"
  ],
  [
    "src/functions/createreactiveinterface.js",
    "file/src/functions/createReactiveInterface.js.html",
    "src/functions/createReactiveInterface.js",
    "file"
  ],
  [
    "src/functions/extendarray.js",
    "file/src/functions/extendArray.js.html",
    "src/functions/extendArray.js",
    "file"
  ],
  [
    "src/functions/setcomputedproperty.js",
    "file/src/functions/setComputedProperty.js.html",
    "src/functions/setComputedProperty.js",
    "file"
  ],
  [
    "src/functions/typechecker.js",
    "file/src/functions/typeChecker.js.html",
    "src/functions/typeChecker.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/types.js",
    "file/src/types.js.html",
    "src/types.js",
    "file"
  ]
]